Fix wifi_hal_common for the case where kernel modules are used
When WIFI_DRIVER_MODULE_PATH is defined, wifi_hal_common.cpp fails
to compile with the following errors:

wifi_hal_common.cpp:68: error: undefined reference to 'init_module(void*, unsigned long, char const*)'
wifi_hal_common.cpp:81: error: undefined reference to 'delete_module(char const*, unsigned int)'

The problem is that this is a C++ source and the extern functions
are have C++ name mangling applied to it:

$ nm $OUT/obj/STATIC_LIBRARIES/libwifi-hal-common_intermediates/libwifi-hal-common.a | grep _module
U _Z11init_modulePvmPKc
U _Z13delete_modulePKcj

These functions must be declared as extern "C" in order to link
successfully with libc.so.

BUG=None
TEST=m -j32

Change-Id: Ic8f15790b5d92ca40eb14a64ace36fd177cc4ea3